"""The converter's user-facing surface: three typed primitives.

    from jevtoo import convert

    jev = convert("openbmb/MiniCPM5-2B-MLX")          # any causal LM
    jev.choice(state, "Which intent?", ["track_order", "cancel_order", ...])
    jev.noul(state, "Is the customer asking for a refund?")
    jev.score(state, "How urgent is this?", ["low", "medium", "high"])

No text is generated by any of these. Each is one forward pass and a read.
"""
from __future__ import annotations

from dataclasses import dataclass

from .backends import load_backend
from .readout import Distribution, render_state

DEFAULT_INSTRUCTION = "Choose the best option."


@dataclass
class DecisionModel:
    """A causal LM wearing a decision-model interface."""

    backend: object
    instruction: str = DEFAULT_INSTRUCTION

    # -- generic ---------------------------------------------------------
    def options(self, state: str, labels: list[str], instructions: str | None = None,
                criteria: dict | list | None = None) -> Distribution:
        prompt = render_state(state, instructions or self.instruction, labels, criteria)
        return self.backend.distribution(prompt, labels)

    # -- the three primitives -------------------------------------------
    def choice(self, state: str, instructions: str, labels: list[str],
               criteria: dict | list | None = None) -> Distribution:
        """PICK-ONE. Returns a distribution over exactly the given labels."""
        return self.options(state, labels, instructions, criteria)

    def noul(self, state: str, question: str, yes: str = "yes", no: str = "no",
             criteria: dict | None = None) -> float:
        """YES/NO GATE. Returns P(positive) renormalised over the two labels.

        Put an explicit no-match or unknown option in `labels` whenever the
        evidence can be missing. Removing that option does not make the model
        uncertain - it makes it confidently answer a question it cannot answer,
        and it will not warn you by spreading probability mass.
        """
        d = self.options(state, [no, yes], question, criteria)
        return d.noul(positive=yes)

    def score(self, state: str, instructions: str, levels: list[str],
              criteria: dict | list | None = None) -> tuple[float, Distribution]:
        """RATE ON A SCALE. Returns (expected value, full distribution)."""
        d = self.options(state, levels, instructions, criteria)
        return d.score(), d


def convert(model_path: str, label_style: str = "spaced",
            instruction: str = DEFAULT_INSTRUCTION) -> DecisionModel:
    """Convert any causal LM into a System-One-style decision model.

    That is the entire conversion: there is no retraining, no fine-tune and no
    new weights. The model is not modified. What changes is the *interface* -
    the state is framed with single-token option labels and the answer is read
    off the final-position distribution instead of being sampled.
    """
    return DecisionModel(backend=load_backend(model_path, label_style=label_style),
                         instruction=instruction)
