"""The converter's user-facing surface: three typed primitives.

    from jevtoo import convert

    jev = convert("openbmb/MiniCPM5-2B-MLX")          # any causal LM
    jev.choice(state, "Which intent?", ["track_order", "cancel_order", ...])
    jev.noul(state, "Is the customer asking for a refund?")
    jev.score(state, "How urgent is this?", ["low", "medium", "high"])

No text is generated by any of these. Each is one forward pass and a read.
"""
from __future__ import annotations

from dataclasses import dataclass

from .backends import load_backend
from .readout import Distribution, render_state

DEFAULT_INSTRUCTION = "Choose the best option."


@dataclass
class DecisionModel:
    """A causal LM wearing a decision-model interface."""

    backend: object
    instruction: str = DEFAULT_INSTRUCTION
    # The distribution behind the most recent primitive. ``noul`` returns a
    # float, so latency, raw mass and the share live here.
    last: Distribution | None = None

    # -- generic ---------------------------------------------------------
    def options(self, state: str, labels: list[str], instructions: str | None = None,
                criteria: dict | list | None = None) -> Distribution:
        prompt = render_state(state, instructions or self.instruction, labels, criteria)
        self.last = self.backend.distribution(prompt, labels)
        return self.last

    def distributions(self, items: list[tuple[str, list[str]]]) -> list[Distribution]:
        """Score ``(prompt, labels)`` pairs. Backends may share a prefix."""
        batch = getattr(self.backend, "distributions", None)
        if callable(batch):
            out = batch(items)
        else:
            out = [self.backend.distribution(prompt, labels) for prompt, labels in items]
        if out:
            self.last = out[-1]
        return out

    # -- the three primitives -------------------------------------------
    def choice(self, state: str, instructions: str, labels: list[str],
               criteria: dict | list | None = None) -> Distribution:
        """PICK-ONE. Returns a distribution over exactly the given labels."""
        return self.options(state, labels, instructions, criteria)

    def noul(self, state: str, question: str, yes: str = "yes", no: str = "no",
             criteria: dict | None = None) -> float:
        """YES/NO GATE. Returns P(positive) renormalised over the two labels.

        The distribution itself — latency, raw mass, share — is ``self.last``.

        Put an explicit no-match or unknown option in `labels` whenever the
        evidence can be missing. Removing that option does not make the model
        uncertain - it makes it confidently answer a question it cannot answer,
        and it will not warn you by spreading probability mass.
        """
        d = self.options(state, [no, yes], question, criteria)
        return d.noul(positive=yes)

    def score(self, state: str, instructions: str, levels: list[str],
              criteria: dict | list | None = None) -> tuple[float, Distribution]:
        """RATE ON A SCALE. Returns (expected value, full distribution)."""
        d = self.options(state, levels, instructions, criteria)
        return d.score(), d


def convert(model_path: str, label_style: str = "spaced",
            instruction: str = DEFAULT_INSTRUCTION) -> DecisionModel:
    """Convert any causal LM into a System-One-style decision model.

    That is the entire conversion: there is no retraining, no fine-tune and no
    new weights. The model is not modified. What changes is the *interface* -
    the state is framed with single-token option labels and the answer is read
    off the final-position distribution instead of being sampled.
    """
    return DecisionModel(backend=load_backend(model_path, label_style=label_style),
                         instruction=instruction)


def convert_gguf(base_url: str = "http://127.0.0.1:8080", n_probs: int = 200,
                 label_style: str = "spaced",
                 instruction: str = DEFAULT_INSTRUCTION) -> DecisionModel:
    """Same conversion over a running llama-server (GGUF weights).

    llama.cpp does not expose full logits over HTTP, so label probabilities are
    read from the server's top-N token list. Always check `jev.backend.coverage()`
    before trusting the numbers: a label that fell outside the top-N is scored 0
    and would silently look like a confident rejection.
    """
    from .backends_gguf import LlamaCppServerBackend

    return DecisionModel(
        backend=LlamaCppServerBackend(base_url, label_style=label_style, n_probs=n_probs),
        instruction=instruction)
